#! /bin/sh

### BEGIN INIT INFO
# Provides:          stone
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Stone Server
# Description:       This script provides a php logic server
#                    to be run in backend of a httpd and should
#                    listen on port 9001 on a properly configured
#                    system
### END INIT INFO

# Source function library
. /lib/lsb/init-functions

NAME=stone-server
DESC="PHP logic server base on swoole"
BASE="/home/apple/qufenqi"
PIDFILE=/run/$NAME.pid
PHPBIN=/usr/bin/php
ENV=production

# Include varnish defaults if available
if [ -f /etc/default/stone ] ; then
        . /etc/default/stone
fi

DAEMON="${PHPBIN} ${BASE}/artisan stone:server --env=${ENV}"

start_stone() {
    log_daemon_msg "Starting $DESC" "$NAME"
    $DAEMON --start
}

stop_stone() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    $DAEMON --stop
}

reload_stone() {
    log_daemon_msg "Reloading $DESC" "$NAME"
    $DAEMON --reload
}

status_stone() {
    exit $?
}

case "$1" in
    start)
        start_stone
        ;;
    stop)
        stop_stone
        ;;
    reload)
        reload_stone
        ;;
    status)
        status_stone
        ;;
    restart|force-reload)
        $0 stop
        $0 start
        ;;
    *)
        log_success_msg "Usage: $0 {start|stop|restart|reload|force-reload}"
        exit 1
        ;;
esac
